// This file was auto-generated by ML.NET Model Builder. 

using System;
using Classificador_de_espécies_de_plantas_irisML.Model;

namespace Classificador_de_espécies_de_plantas_irisML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Id = 1F,
                SepalLengthCm = 5.1F,
                SepalWidthCm = 3.5F,
                PetalLengthCm = 1.4F,
                PetalWidthCm = 0.2F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Species with predicted Species from sample data...\n\n");
            Console.WriteLine($"Id: {sampleData.Id}");
            Console.WriteLine($"SepalLengthCm: {sampleData.SepalLengthCm}");
            Console.WriteLine($"SepalWidthCm: {sampleData.SepalWidthCm}");
            Console.WriteLine($"PetalLengthCm: {sampleData.PetalLengthCm}");
            Console.WriteLine($"PetalWidthCm: {sampleData.PetalWidthCm}");
            Console.WriteLine($"\n\nPredicted Species value {predictionResult.Prediction} \nPredicted Species scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
